# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14bbbb30bea5be91167146dedc32dd18c5b12c7ab8b931748a0795425b65b09e8c03feb51d1e021b796438b8d6d0ff3080e806c7313808443fe7c3bb4c1bf1e5

test:
  secret_key_base: 772f24d9ddfa366277c867c5e8fe223a4fb4937ab5ae848ae8c1946f0fcd17c3c27f705d890f8cfec842bd359ccb459e613236bd39cc42a79af080d30a8ebe1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
